name: Cache Envato Redux Catalog
on: 
  workflow_dispatch:
  schedule:
  - cron:  '0 0 * * *'
jobs:
  composer:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: version
        run: |
          echo "builddate=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v1
      - uses: nanasess/setup-php@master
        with:
          php-version: '8.0'

      - run: php ./run.php ${{ secrets.ENVATO_TOKEN }}
        env:
          ENVATO_TOKEN: ${{secrets.ENVATO_TOKEN}}

      - run: git config --global user.email "support@svlstudios.com" && git config --global user.name "SVL Studios"
      - run: git add -f -A
      - run: git commit -m "Envato Redux Catalog Update: ${{ steps.version.outputs.builddate }} (Build $GITHUB_RUN_NUMBER)" || echo "Nothing to commit."
      - run: git push "https://x-access-token:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY" HEAD:main
      
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
